version: '3.3'
services: 
    banco:
        image: mysql:5.6
        hostname: banco
        environment: 
            - MYSQL_ROOT_PASSWORD=SafiraLabApp
            - MYSQL_DATABASE=safira
        ports: 
            - "3306:3306"
        volumes: 
            - ./data:/var/lib/mysql
        networks: 
            - backend
    safira-api:
        build: ./teste_tomcat
        environment: 
            WAIT_HOSTS: localhost:3306
        ports: 
            - "8080:8080"
        depends_on:
            - banco
        networks: 
            - frontend
            - backend
    safira-lab:
        build: ./frontend
        ports: 
            - "5000:5000"
        depends_on: 
            - safira-api
        networks:
            - frontend
networks: 
    frontend:
        driver: bridge
    backend:
        driver: bridge